// ============================================
// PRIVILEGES DATA - Investor Privileges System
// ============================================

// Main Categories (Primary Tabs)
const mainCategories = [
    {
        id: 'movie',
        label: 'Movies',
        labelTh: 'หนัง',
        icon: 'fa-film',
        color: 'from-red-500 to-orange-500'
    },
    {
        id: 'game',
        label: 'Games',
        labelTh: 'เกมส์',
        icon: 'fa-gamepad',
        color: 'from-purple-500 to-pink-500'
    }
];

// Sub-Categories for Privileges
const privilegeCategories = [
    // Movie Sub-Categories
    {
        id: 'all',
        label: 'All Privileges',
        labelTh: 'สิทธิพิเศษทั้งหมด',
        icon: 'fa-layer-group',
        color: 'from-primary to-secondary',
        description: 'View all available privileges',
        descriptionTh: 'ดูสิทธิพิเศษทั้งหมด',
        mainCategory: 'all'
    },
    {
        id: 'movie-tickets',
        label: 'Movie Tickets',
        labelTh: 'บัตรชมภาพยนตร์',
        icon: 'fa-ticket-alt',
        color: 'from-red-500 to-orange-500',
        description: 'Exclusive movie screening tickets',
        descriptionTh: 'บัตรชมภาพยนตร์พิเศษ',
        mainCategory: 'movie'
    },
    {
        id: 'meet-greet',
        label: 'Meet & Greet',
        labelTh: 'พบทีมผู้สร้างสรรค์',
        icon: 'fa-users',
        color: 'from-blue-500 to-cyan-500',
        description: 'Meet producers, directors & actors',
        descriptionTh: 'พบโปรดิวเซอร์ ผู้กำกับ นักแสดง',
        mainCategory: 'movie'
    },
    {
        id: 'credits',
        label: 'Movie Credits',
        labelTh: 'เครดิตท้ายภาพยนตร์',
        icon: 'fa-film',
        color: 'from-yellow-500 to-amber-500',
        description: 'Your name in movie credits',
        descriptionTh: 'ชื่อของคุณในเครดิตท้ายภาพยนตร์',
        mainCategory: 'movie'
    },
    {
        id: 'merchandise',
        label: 'Merchandise',
        labelTh: 'สินค้าที่ระลึก',
        icon: 'fa-gift',
        color: 'from-green-500 to-emerald-500',
        description: 'Exclusive merchandise & collectibles',
        descriptionTh: 'สินค้าที่ระลึกพิเศษ',
        mainCategory: 'movie'
    },
    {
        id: 'behind-scenes',
        label: 'Behind the Scenes',
        labelTh: 'ชมเบื้องหลัง เยี่ยมกองถ่าย',
        icon: 'fa-camera',
        color: 'from-primary to-primary-light',
        description: 'Set visits & behind the scenes access',
        descriptionTh: 'เข้าชมกองถ่ายและเบื้องหลัง',
        mainCategory: 'movie'
    },
    {
        id: 'other',
        label: 'Other Privileges',
        labelTh: 'สิทธิพิเศษอื่นๆ',
        icon: 'fa-star',
        color: 'from-secondary to-secondary-light',
        description: 'More exclusive privileges',
        descriptionTh: 'สิทธิพิเศษอื่นๆ มากมาย',
        mainCategory: 'movie'
    },
    // Game Sub-Categories
    {
        id: 'game-items',
        label: 'In-Game Items',
        labelTh: 'ไอเทมในเกม',
        icon: 'fa-gem',
        color: 'from-purple-500 to-indigo-500',
        description: 'Exclusive in-game items',
        descriptionTh: 'ไอเทมในเกมพิเศษ',
        mainCategory: 'game'
    },
    {
        id: 'game-credits',
        label: 'Game Credits',
        labelTh: 'เครดิตในเกม',
        icon: 'fa-coins',
        color: 'from-yellow-400 to-orange-400',
        description: 'Your name in game credits',
        descriptionTh: 'ชื่อของคุณในเครดิตเกม',
        mainCategory: 'game'
    },
    {
        id: 'game-meet-greet',
        label: 'Meet Developers',
        labelTh: 'พบนักพัฒนาเกม',
        icon: 'fa-laptop-code',
        color: 'from-cyan-500 to-blue-500',
        description: 'Meet game developers',
        descriptionTh: 'พบปะทีมพัฒนาเกม',
        mainCategory: 'game'
    },
    {
        id: 'game-merchandise',
        label: 'Game Merchandise',
        labelTh: 'สินค้าที่ระลึกเกม',
        icon: 'fa-tshirt',
        color: 'from-pink-500 to-rose-500',
        description: 'Exclusive game merchandise',
        descriptionTh: 'สินค้าที่ระลึกจากเกม',
        mainCategory: 'game'
    },
    {
        id: 'early-access',
        label: 'Early Access',
        labelTh: 'เข้าถึงก่อน',
        icon: 'fa-rocket',
        color: 'from-green-400 to-teal-500',
        description: 'Early access to games',
        descriptionTh: 'เข้าเล่นเกมก่อนเปิดตัว',
        mainCategory: 'game'
    }
];

const privilegePackages = [
    // Movie Tickets Category
    {
        id: 101,
        title: 'Premiere Night VIP Ticket',
        titleTh: 'บัตร VIP รอบปฐมทัศน์',
        subtitle: 'Exclusive premiere screening',
        subtitleTh: 'ชมภาพยนตร์รอบปฐมทัศน์สุดพิเศษ',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: '../images/privilege_movie_premiere.png',
        price: 500,
        rating: 4.9,
        reviews: 156,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        eventDate: '2024-06-15',
        venue: 'Major Cineplex Paragon',
        description: 'Experience the premiere night with VIP seating, welcome drinks, and exclusive meet & greet opportunity.',
        descriptionTh: 'สัมผัสประสบการณ์รอบปฐมทัศน์พร้อมที่นั่ง VIP เครื่องดื่มต้อนรับ และโอกาสพบปะทีมนักแสดง',
        conditions: ['Valid for 1 person', 'Non-transferable', 'Must present QR code at venue'],
        conditionsTh: ['ใช้ได้ 1 ท่าน', 'ไม่สามารถโอนสิทธิ์ได้', 'ต้องแสดง QR code ที่สถานที่']
    },
    {
        id: 102,
        title: 'Couple Movie Pass',
        titleTh: 'บัตรชมภาพยนตร์คู่รัก',
        subtitle: '2 tickets for any screening',
        subtitleTh: 'บัตร 2 ใบสำหรับทุกรอบฉาย',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: '../images/privilege_couple_movie.png',
        price: 300,
        rating: 4.7,
        reviews: 89,
        isPhysical: false,
        tier: 'silver',
        movieName: 'Any FLIPS Production',
        movieNameTh: 'ภาพยนตร์ FLIPS ทุกเรื่อง',
        description: 'Two premium tickets for any FLIPS production movie screening.',
        descriptionTh: 'บัตรพรีเมียม 2 ใบสำหรับภาพยนตร์ FLIPS ทุกเรื่อง',
        conditions: ['Valid for 2 persons', 'Valid for 6 months', 'Subject to seat availability'],
        conditionsTh: ['ใช้ได้ 2 ท่าน', 'ใช้ได้ภายใน 6 เดือน', 'ขึ้นอยู่กับที่นั่งว่าง']
    },
    {
        id: 103,
        title: 'Annual Movie Pass',
        titleTh: 'บัตรสมาชิกชมภาพยนตร์รายปี',
        subtitle: 'Unlimited movies for 1 year',
        subtitleTh: 'ดูหนังไม่จำกัดตลอด 1 ปี',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: '../images/privilege_annual_pass.png',
        price: 2000,
        rating: 5.0,
        reviews: 45,
        isPhysical: true,
        tier: 'gold',
        description: 'Unlimited access to all FLIPS production movies for one full year.',
        descriptionTh: 'เข้าชมภาพยนตร์ FLIPS ได้ไม่จำกัดตลอด 1 ปีเต็ม',
        conditions: ['Valid for 1 person', '12 months validity', 'Physical card will be shipped'],
        conditionsTh: ['ใช้ได้ 1 ท่าน', 'ใช้ได้ 12 เดือน', 'จัดส่งบัตรสมาชิกถึงบ้าน']
    },

    // Meet & Greet Category
    {
        id: 201,
        title: 'Director Meet & Greet',
        titleTh: 'พบปะผู้กำกับ',
        subtitle: 'Exclusive session with the director',
        subtitleTh: 'พบปะผู้กำกับแบบเอ็กซ์คลูซีฟ',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: '../images/privilege_meet_director.png',
        price: 1500,
        rating: 4.9,
        reviews: 32,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-07-20',
        venue: 'FLIPS Studio Bangkok',
        description: 'A once-in-a-lifetime opportunity to meet the director and discuss filmmaking.',
        descriptionTh: 'โอกาสครั้งหนึ่งในชีวิตที่จะพบผู้กำกับและพูดคุยเรื่องการสร้างภาพยนตร์',
        conditions: ['Limited to 20 participants', 'Photo opportunity included', 'Light refreshments provided'],
        conditionsTh: ['จำกัด 20 ท่าน', 'รวมถ่ายรูปร่วมกัน', 'มีอาหารว่างบริการ']
    },
    {
        id: 202,
        title: 'Cast Photo Session',
        titleTh: 'ถ่ายรูปกับนักแสดง',
        subtitle: 'Photo with main cast members',
        subtitleTh: 'ถ่ายรูปกับนักแสดงนำ',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: '../images/privilege_meet_cast.png',
        price: 800,
        rating: 4.8,
        reviews: 67,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-08-10',
        venue: 'FLIPS Studio Bangkok',
        description: 'Get your photo taken with the main cast members of the movie.',
        descriptionTh: 'ถ่ายรูปกับนักแสดงนำของภาพยนตร์',
        conditions: ['1 photo per person', 'Digital copy provided', 'Meet at designated time'],
        conditionsTh: ['1 รูปต่อท่าน', 'ได้รับไฟล์ดิจิตอล', 'นัดพบตามเวลาที่กำหนด']
    },
    {
        id: 203,
        title: 'Producer Dinner Event',
        titleTh: 'ดินเนอร์กับโปรดิวเซอร์',
        subtitle: 'Exclusive dinner with the producer',
        subtitleTh: 'รับประทานอาหารค่ำกับโปรดิวเซอร์',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: '../images/privilege_meet_private.png',
        price: 3000,
        rating: 5.0,
        reviews: 12,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-09-05',
        venue: 'The Peninsula Bangkok',
        description: 'An intimate dinner experience with the producer to discuss the creative process.',
        descriptionTh: 'ประสบการณ์รับประทานอาหารค่ำแบบส่วนตัวกับโปรดิวเซอร์',
        conditions: ['Limited to 10 guests', 'Formal dress code', 'Full course dinner included'],
        conditionsTh: ['จำกัด 10 ท่าน', 'แต่งกายสุภาพ', 'รวมอาหารค่ำเต็มคอร์ส']
    },

    // Movie Credits Category
    {
        id: 301,
        title: 'Special Thanks Credit',
        titleTh: 'เครดิต Special Thanks',
        subtitle: 'Your name in Special Thanks section',
        subtitleTh: 'ชื่อของคุณในส่วน Special Thanks',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: '../images/privilege_credits.png',
        price: 1000,
        rating: 4.8,
        reviews: 234,
        isPhysical: false,
        tier: 'silver',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'Have your name appear in the Special Thanks section of the movie credits.',
        descriptionTh: 'ชื่อของคุณจะปรากฏในส่วน Special Thanks ของเครดิตท้ายภาพยนตร์',
        conditions: ['Name as registered', 'Permanent credit', 'Certificate provided'],
        conditionsTh: ['ใช้ชื่อตามที่ลงทะเบียน', 'เครดิตถาวร', 'ได้รับใบประกาศนียบัตร']
    },
    {
        id: 302,
        title: 'Associate Producer Credit',
        titleTh: 'เครดิต Associate Producer',
        subtitle: 'Your name as Associate Producer',
        subtitleTh: 'ชื่อของคุณในฐานะ Associate Producer',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: '../images/privilege_credits_producer.png',
        price: 5000,
        rating: 5.0,
        reviews: 18,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'Be credited as an Associate Producer in the official movie credits.',
        descriptionTh: 'ได้รับเครดิตในฐานะ Associate Producer ในเครดิตภาพยนตร์อย่างเป็นทางการ',
        conditions: ['Official credit', 'IMDb listing', 'Premiere invitation included'],
        conditionsTh: ['เครดิตอย่างเป็นทางการ', 'ลงรายชื่อใน IMDb', 'รวมบัตรเชิญรอบปฐมทัศน์']
    },
    {
        id: 303,
        title: 'Executive Producer Credit',
        titleTh: 'เครดิต Executive Producer',
        subtitle: 'Top tier producer credit',
        subtitleTh: 'เครดิตโปรดิวเซอร์ระดับสูงสุด',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: '../images/privilege_credits_special.png',
        price: 15000,
        rating: 5.0,
        reviews: 5,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'The highest honor - be credited as Executive Producer with full privileges.',
        descriptionTh: 'เกียรติยศสูงสุด - ได้รับเครดิตในฐานะ Executive Producer พร้อมสิทธิพิเศษเต็มรูปแบบ',
        conditions: ['Prominent credit placement', 'All premiere events access', 'Private screening rights'],
        conditionsTh: ['เครดิตในตำแหน่งเด่น', 'เข้าร่วมงานปฐมทัศน์ทุกงาน', 'สิทธิ์ฉายภาพยนตร์ส่วนตัว']
    },

    // Merchandise Category
    {
        id: 401,
        title: 'Movie Poster Collection',
        titleTh: 'คอลเลคชั่นโปสเตอร์',
        subtitle: 'Signed limited edition posters',
        subtitleTh: 'โปสเตอร์ลิมิเต็ดพร้อมลายเซ็น',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: '../images/privilege_merch_poster.png',
        price: 400,
        rating: 4.7,
        reviews: 156,
        isPhysical: true,
        tier: 'silver',
        description: 'Set of 3 limited edition movie posters signed by the cast.',
        descriptionTh: 'ชุดโปสเตอร์ลิมิเต็ด 3 แบบพร้อมลายเซ็นนักแสดง',
        conditions: ['Ships within 7 days', 'Certificate of authenticity', 'Protective tube packaging'],
        conditionsTh: ['จัดส่งภายใน 7 วัน', 'ใบรับรองความแท้', 'บรรจุในหลอดป้องกัน']
    },
    {
        id: 402,
        title: 'Prop Replica Set',
        titleTh: 'ชุดพร็อพจำลอง',
        subtitle: 'Authentic prop replicas',
        subtitleTh: 'พร็อพจำลองจากภาพยนตร์',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: '../images/privilege_merch_tshirt.png',
        price: 800,
        rating: 4.9,
        reviews: 78,
        isPhysical: true,
        tier: 'gold',
        description: 'High-quality replica props used in the movie production.',
        descriptionTh: 'พร็อพจำลองคุณภาพสูงจากกองถ่ายภาพยนตร์',
        conditions: ['Handcrafted items', 'Display case included', 'Limited edition numbering'],
        conditionsTh: ['ทำมืออย่างประณีต', 'รวมกล่องแสดง', 'มีหมายเลขลิมิเต็ด']
    },
    {
        id: 403,
        title: 'Premium Merchandise Box',
        titleTh: 'กล่องสินค้าพรีเมียม',
        subtitle: 'Complete collector box set',
        subtitleTh: 'ชุดกล่องสะสมครบเซ็ต',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: '../images/privilege_merch_premium.png',
        price: 1500,
        rating: 5.0,
        reviews: 34,
        isPhysical: true,
        tier: 'gold',
        description: 'Complete box set with T-shirt, poster, art book, and exclusive items.',
        descriptionTh: 'กล่องครบเซ็ตพร้อมเสื้อยืด โปสเตอร์ อาร์ตบุ๊ค และของพิเศษ',
        conditions: ['All items included', 'Premium packaging', 'Numbered collector edition'],
        conditionsTh: ['รวมสินค้าทั้งหมด', 'บรรจุภัณฑ์พรีเมียม', 'เวอร์ชั่นสะสมมีหมายเลข']
    },

    // Behind the Scenes Category
    {
        id: 501,
        title: 'Set Visit Pass',
        titleTh: 'บัตรเยี่ยมชมกองถ่าย',
        subtitle: 'Full day set visit',
        subtitleTh: 'เยี่ยมชมกองถ่ายเต็มวัน',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: '../images/privilege_bts_set.png',
        price: 2000,
        rating: 5.0,
        reviews: 23,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-08-15',
        venue: 'FLIPS Film Studios',
        description: 'Exclusive access to visit the movie set during production.',
        descriptionTh: 'สิทธิ์พิเศษในการเยี่ยมชมกองถ่ายระหว่างการผลิต',
        conditions: ['NDA required', 'No personal photography', 'Lunch provided'],
        conditionsTh: ['ต้องเซ็นสัญญารักษาความลับ', 'ห้ามถ่ายรูปส่วนตัว', 'รวมอาหารกลางวัน']
    },
    {
        id: 502,
        title: 'Behind the Scenes Documentary',
        titleTh: 'สารคดีเบื้องหลัง',
        subtitle: 'Exclusive documentary access',
        subtitleTh: 'เข้าถึงสารคดีพิเศษ',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: '../images/privilege_bts_makeup.png',
        price: 300,
        rating: 4.8,
        reviews: 189,
        isPhysical: false,
        tier: 'bronze',
        description: 'Access to exclusive behind-the-scenes documentary content.',
        descriptionTh: 'เข้าถึงเนื้อหาสารคดีเบื้องหลังพิเศษ',
        conditions: ['Digital streaming access', 'Lifetime access', 'HD quality'],
        conditionsTh: ['รับชมผ่านสตรีมมิ่ง', 'เข้าถึงตลอดชีพ', 'คุณภาพ HD']
    },
    {
        id: 503,
        title: 'VFX Studio Tour',
        titleTh: 'ทัวร์สตูดิโอ VFX',
        subtitle: 'Visual effects studio experience',
        subtitleTh: 'สัมผัสสตูดิโอเอฟเฟกต์พิเศษ',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: '../images/privilege_bts_vip.png',
        price: 1200,
        rating: 4.9,
        reviews: 45,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-09-20',
        venue: 'FLIPS VFX Studio',
        description: 'Tour the VFX studio and see how movie magic is created.',
        descriptionTh: 'ทัวร์สตูดิโอ VFX และชมการสร้างมายากลภาพยนตร์',
        conditions: ['2-hour guided tour', 'Small group experience', 'Demonstration included'],
        conditionsTh: ['ทัวร์พร้อมไกด์ 2 ชั่วโมง', 'กลุ่มเล็กเป็นกันเอง', 'รวมการสาธิต']
    },

    // Other Privileges Category
    {
        id: 601,
        title: 'Script Reading Session',
        titleTh: 'เซสชั่นอ่านบท',
        subtitle: 'Attend a live script reading',
        subtitleTh: 'ร่วมฟังการอ่านบทสด',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: '../images/privilege_wrap_party.png',
        price: 600,
        rating: 4.7,
        reviews: 67,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-07-10',
        venue: 'FLIPS Theater',
        description: 'Attend an exclusive script reading with the cast.',
        descriptionTh: 'ร่วมฟังการอ่านบทพิเศษกับทีมนักแสดง',
        conditions: ['Limited seating', 'Q&A session included', 'Refreshments served'],
        conditionsTh: ['ที่นั่งจำกัด', 'รวมเซสชั่นถาม-ตอบ', 'มีเครื่องดื่มบริการ']
    },
    {
        id: 602,
        title: 'Soundtrack Album',
        titleTh: 'อัลบั้มเพลงประกอบ',
        subtitle: 'Exclusive signed soundtrack',
        subtitleTh: 'อัลบั้มเพลงประกอบพร้อมลายเซ็น',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: '../images/privilege_screening.png',
        price: 350,
        rating: 4.6,
        reviews: 123,
        isPhysical: true,
        tier: 'bronze',
        description: 'Limited edition soundtrack album signed by the composer.',
        descriptionTh: 'อัลบั้มเพลงประกอบลิมิเต็ดพร้อมลายเซ็นนักแต่งเพลง',
        conditions: ['Vinyl + Digital', 'Signed by composer', 'Shipping included'],
        conditionsTh: ['แผ่นเสียง + ดิจิตอล', 'ลายเซ็นนักแต่งเพลง', 'รวมค่าจัดส่ง']
    },
    {
        id: 603,
        title: 'Investor Newsletter',
        titleTh: 'จดหมายข่าวผู้ลงทุน',
        subtitle: 'Exclusive monthly updates',
        subtitleTh: 'อัพเดทรายเดือนพิเศษ',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: '../images/privilege_mystery.png',
        price: 100,
        rating: 4.5,
        reviews: 234,
        isPhysical: false,
        tier: 'bronze',
        description: 'Monthly exclusive newsletter with insider updates and early announcements.',
        descriptionTh: 'จดหมายข่าวรายเดือนพร้อมข้อมูลวงในและประกาศล่วงหน้า',
        conditions: ['12-month subscription', 'Digital delivery', 'Early access to news'],
        conditionsTh: ['สมัครสมาชิก 12 เดือน', 'ส่งทางดิจิตอล', 'รับข่าวก่อนใคร']
    },

    // ============================================
    // GAME PRIVILEGES
    // ============================================

    // In-Game Items Category
    {
        id: 701,
        title: 'Legendary Weapon Skin',
        titleTh: 'สกินอาวุธระดับตำนาน',
        subtitle: 'Exclusive rare weapon skin',
        subtitleTh: 'สกินอาวุธหายากสุดพิเศษ',
        category: 'game-items',
        categoryLabel: 'In-Game Items',
        categoryLabelTh: 'ไอเทมในเกม',
        image: '../images/privilege_game_weapon.png',
        price: 800,
        rating: 4.9,
        reviews: 234,
        isPhysical: false,
        tier: 'gold',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'Get an exclusive legendary weapon skin that glows with special effects.',
        descriptionTh: 'รับสกินอาวุธระดับตำนานที่เรืองแสงพร้อมเอฟเฟกต์พิเศษ',
        conditions: ['Account binding required', 'One-time redemption', 'Permanent unlock'],
        conditionsTh: ['ต้องผูกบัญชี', 'แลกได้ครั้งเดียว', 'ปลดล็อคถาวร']
    },
    {
        id: 702,
        title: 'Character Bundle Pack',
        titleTh: 'แพ็คตัวละครพิเศษ',
        subtitle: '5 exclusive characters',
        subtitleTh: '5 ตัวละครสุดพิเศษ',
        category: 'game-items',
        categoryLabel: 'In-Game Items',
        categoryLabelTh: 'ไอเทมในเกม',
        image: '../images/privilege_game_character.png',
        price: 1500,
        rating: 5.0,
        reviews: 156,
        isPhysical: false,
        tier: 'gold',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'Unlock 5 exclusive playable characters with unique abilities.',
        descriptionTh: 'ปลดล็อค 5 ตัวละครพิเศษพร้อมความสามารถเฉพาะตัว',
        conditions: ['All characters unlocked', 'Includes special emotes', 'Cross-platform'],
        conditionsTh: ['ได้ตัวละครทั้งหมด', 'รวมท่าทางพิเศษ', 'ใช้ได้ทุกแพลตฟอร์ม']
    },

    // Game Credits Category
    {
        id: 703,
        title: 'Supporter Credit',
        titleTh: 'เครดิต Supporter',
        subtitle: 'Your name in game credits',
        subtitleTh: 'ชื่อของคุณในเครดิตเกม',
        category: 'game-credits',
        categoryLabel: 'Game Credits',
        categoryLabelTh: 'เครดิตในเกม',
        image: '../images/privilege_game_credits.png',
        price: 500,
        rating: 4.7,
        reviews: 89,
        isPhysical: false,
        tier: 'silver',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'Have your name displayed in the game credits as a Supporter.',
        descriptionTh: 'ชื่อของคุณจะปรากฏในเครดิตเกมในฐานะ Supporter',
        conditions: ['Permanent credit', 'Name as registered', 'Digital certificate'],
        conditionsTh: ['เครดิตถาวร', 'ใช้ชื่อตามที่ลงทะเบียน', 'ใบประกาศดิจิตอล']
    },
    {
        id: 704,
        title: 'Executive Backer Credit',
        titleTh: 'เครดิต Executive Backer',
        subtitle: 'Premium credit placement',
        subtitleTh: 'เครดิตตำแหน่งพิเศษ',
        category: 'game-credits',
        categoryLabel: 'Game Credits',
        categoryLabelTh: 'เครดิตในเกม',
        image: '../images/privilege_game_credits_exec.png',
        price: 3000,
        rating: 5.0,
        reviews: 23,
        isPhysical: false,
        tier: 'gold',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'Get premium credit placement as Executive Backer with in-game NPC named after you.',
        descriptionTh: 'รับเครดิตตำแหน่งพิเศษในฐานะ Executive Backer พร้อม NPC ในเกมที่ตั้งชื่อตามคุณ',
        conditions: ['Prominent placement', 'Custom NPC', 'All games access'],
        conditionsTh: ['ตำแหน่งเด่น', 'NPC ตั้งชื่อตามคุณ', 'เข้าถึงเกมทั้งหมด']
    },

    // Meet Developers Category
    {
        id: 705,
        title: 'Developer Q&A Session',
        titleTh: 'เซสชั่นถามตอบกับนักพัฒนา',
        subtitle: 'Online Q&A with dev team',
        subtitleTh: 'ถามตอบออนไลน์กับทีมพัฒนา',
        category: 'game-meet-greet',
        categoryLabel: 'Meet Developers',
        categoryLabelTh: 'พบนักพัฒนาเกม',
        image: '../images/privilege_game_qa.png',
        price: 600,
        rating: 4.8,
        reviews: 67,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-10-15',
        venue: 'Online (Zoom)',
        description: 'Join an exclusive online Q&A session with the game development team.',
        descriptionTh: 'ร่วมเซสชั่นถามตอบออนไลน์พิเศษกับทีมพัฒนาเกม',
        conditions: ['90-minute session', 'Limited to 30 people', 'Recording provided'],
        conditionsTh: ['เซสชั่น 90 นาที', 'จำกัด 30 คน', 'มีบันทึกวิดีโอให้']
    },
    {
        id: 706,
        title: 'Studio Visit',
        titleTh: 'เยี่ยมชมสตูดิโอเกม',
        subtitle: 'Visit the game studio',
        subtitleTh: 'เข้าชมสตูดิโอพัฒนาเกม',
        category: 'game-meet-greet',
        categoryLabel: 'Meet Developers',
        categoryLabelTh: 'พบนักพัฒนาเกม',
        image: '../images/privilege_game_studio.png',
        price: 2500,
        rating: 5.0,
        reviews: 12,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-11-20',
        venue: 'FLIPS Game Studio Bangkok',
        description: 'Get an exclusive tour of our game development studio and meet the team.',
        descriptionTh: 'ทัวร์พิเศษสตูดิโอพัฒนาเกมและพบทีมงาน',
        conditions: ['Full day experience', 'Lunch provided', 'Exclusive merchandise'],
        conditionsTh: ['ประสบการณ์เต็มวัน', 'รวมอาหารกลางวัน', 'ของที่ระลึกพิเศษ']
    },

    // Game Merchandise Category
    {
        id: 707,
        title: 'Limited Edition Figurine',
        titleTh: 'ฟิกเกอร์ลิมิเต็ด',
        subtitle: 'Collectible game figurine',
        subtitleTh: 'ฟิกเกอร์สะสมจากเกม',
        category: 'game-merchandise',
        categoryLabel: 'Game Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึกเกม',
        image: '../images/privilege_game_figurine.png',
        price: 1200,
        rating: 4.9,
        reviews: 89,
        isPhysical: true,
        tier: 'gold',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'High-quality limited edition figurine of the main character.',
        descriptionTh: 'ฟิกเกอร์คุณภาพสูงลิมิเต็ดของตัวละครหลัก',
        conditions: ['Numbered edition', 'Certificate included', 'Premium packaging'],
        conditionsTh: ['มีหมายเลขกำกับ', 'ใบรับรองความแท้', 'บรรจุภัณฑ์พรีเมียม']
    },
    {
        id: 708,
        title: 'Artbook & Soundtrack',
        titleTh: 'อาร์ตบุ๊คและเพลงประกอบ',
        subtitle: 'Game art & music collection',
        subtitleTh: 'รวมงานศิลป์และเพลงจากเกม',
        category: 'game-merchandise',
        categoryLabel: 'Game Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึกเกม',
        image: '../images/privilege_game_artbook.png',
        price: 700,
        rating: 4.8,
        reviews: 134,
        isPhysical: true,
        tier: 'silver',
        gameName: 'Cyber Warriors',
        gameNameTh: 'ไซเบอร์ วอร์ริเออร์',
        description: 'Beautiful artbook with concept art plus original soundtrack on CD.',
        descriptionTh: 'อาร์ตบุ๊คสวยงามพร้อมภาพคอนเซ็ปต์และแผ่น CD เพลงประกอบ',
        conditions: ['Hardcover book', '2 audio CDs', 'Developer commentary'],
        conditionsTh: ['หนังสือปกแข็ง', 'แผ่น CD 2 แผ่น', 'คอมเมนต์จากนักพัฒนา']
    },

    // Early Access Category
    {
        id: 709,
        title: 'Closed Beta Access',
        titleTh: 'เข้าถึง Closed Beta',
        subtitle: 'Play before everyone else',
        subtitleTh: 'เล่นก่อนใครๆ',
        category: 'early-access',
        categoryLabel: 'Early Access',
        categoryLabelTh: 'เข้าถึงก่อน',
        image: '../images/privilege_game_beta.png',
        price: 400,
        rating: 4.9,
        reviews: 256,
        isPhysical: false,
        tier: 'silver',
        gameName: 'Project Nova',
        gameNameTh: 'โปรเจค โนวา',
        eventDate: '2025-01-15',
        description: 'Get exclusive access to closed beta testing before public launch.',
        descriptionTh: 'เข้าถึง Closed Beta ก่อนเปิดให้สาธารณะ',
        conditions: ['2-week early access', 'Beta tester badge', 'Feedback channel'],
        conditionsTh: ['เข้าถึงก่อน 2 สัปดาห์', 'แบดจ์ผู้ทดสอบ', 'ช่องทางแจ้งข้อเสนอแนะ']
    },
    {
        id: 710,
        title: 'Founder\'s Pack',
        titleTh: 'แพ็ค Founder',
        subtitle: 'Ultimate early supporter pack',
        subtitleTh: 'แพ็คสุดพิเศษสำหรับผู้สนับสนุน',
        category: 'early-access',
        categoryLabel: 'Early Access',
        categoryLabelTh: 'เข้าถึงก่อน',
        image: '../images/privilege_game_founder.png',
        price: 2000,
        rating: 5.0,
        reviews: 45,
        isPhysical: false,
        tier: 'gold',
        gameName: 'Project Nova',
        gameNameTh: 'โปรเจค โนวา',
        eventDate: '2025-01-01',
        description: 'The complete founder package with alpha access, exclusive items, and lifetime perks.',
        descriptionTh: 'แพ็ค Founder ครบเซ็ตพร้อม Alpha access, ไอเทมพิเศษ และสิทธิประโยชน์ตลอดชีพ',
        conditions: ['Alpha & Beta access', 'Founder title', 'All future DLC free'],
        conditionsTh: ['เข้าถึง Alpha และ Beta', 'ยศ Founder', 'DLC ในอนาคตฟรี']
    }
];

// Helper function to get mainCategory from category id
function getMainCategoryFromCategory(categoryId) {
    const category = privilegeCategories.find(c => c.id === categoryId);
    return category ? category.mainCategory : 'movie';
}

// Calculate category counts with mainCategory support
function getCategoryCounts(mainCategoryFilter = null) {
    const counts = {};
    const packages = typeof getActivePackages === 'function' ? getActivePackages() : privilegePackages;

    privilegeCategories.forEach(cat => {
        if (cat.id === 'all') {
            if (mainCategoryFilter && mainCategoryFilter !== 'all') {
                // Count only packages in this main category
                counts[cat.id] = packages.filter(p => {
                    const pMainCat = getMainCategoryFromCategory(p.category);
                    return pMainCat === mainCategoryFilter;
                }).length;
            } else {
                counts[cat.id] = packages.length;
            }
        } else {
            counts[cat.id] = packages.filter(p => p.category === cat.id).length;
        }
    });
    return counts;
}

