// ============================================
// PRIVILEGES DATA - Investor Privileges System
// ============================================

const privilegeCategories = [
    {
        id: 'all',
        label: 'All Privileges',
        labelTh: 'สิทธิพิเศษทั้งหมด',
        icon: 'fa-layer-group',
        color: 'from-purple-500 to-pink-500',
        description: 'View all available privileges',
        descriptionTh: 'ดูสิทธิพิเศษทั้งหมด'
    },
    {
        id: 'movie-tickets',
        label: 'Movie Tickets',
        labelTh: 'บัตรชมภาพยนตร์',
        icon: 'fa-ticket-alt',
        color: 'from-red-500 to-orange-500',
        description: 'Exclusive movie screening tickets',
        descriptionTh: 'บัตรชมภาพยนตร์พิเศษ'
    },
    {
        id: 'meet-greet',
        label: 'Meet & Greet',
        labelTh: 'พบทีมผู้สร้างสรรค์',
        icon: 'fa-users',
        color: 'from-blue-500 to-cyan-500',
        description: 'Meet producers, directors & actors',
        descriptionTh: 'พบโปรดิวเซอร์ ผู้กำกับ นักแสดง'
    },
    {
        id: 'credits',
        label: 'Movie Credits',
        labelTh: 'เครดิตท้ายภาพยนตร์',
        icon: 'fa-film',
        color: 'from-yellow-500 to-amber-500',
        description: 'Your name in movie credits',
        descriptionTh: 'ชื่อของคุณในเครดิตท้ายภาพยนตร์'
    },
    {
        id: 'merchandise',
        label: 'Merchandise',
        labelTh: 'สินค้าที่ระลึก',
        icon: 'fa-gift',
        color: 'from-green-500 to-emerald-500',
        description: 'Exclusive merchandise & collectibles',
        descriptionTh: 'สินค้าที่ระลึกพิเศษ'
    },
    {
        id: 'behind-scenes',
        label: 'Behind the Scenes',
        labelTh: 'ชมเบื้องหลัง เยี่ยมกองถ่าย',
        icon: 'fa-camera',
        color: 'from-indigo-500 to-purple-500',
        description: 'Set visits & behind the scenes access',
        descriptionTh: 'เข้าชมกองถ่ายและเบื้องหลัง'
    },
    {
        id: 'other',
        label: 'Other Privileges',
        labelTh: 'สิทธิพิเศษอื่นๆ',
        icon: 'fa-star',
        color: 'from-pink-500 to-rose-500',
        description: 'More exclusive privileges',
        descriptionTh: 'สิทธิพิเศษอื่นๆ มากมาย'
    }
];

const privilegePackages = [
    // Movie Tickets Category
    {
        id: 101,
        title: 'Premiere Night VIP Ticket',
        titleTh: 'บัตร VIP รอบปฐมทัศน์',
        subtitle: 'Exclusive premiere screening',
        subtitleTh: 'ชมภาพยนตร์รอบปฐมทัศน์สุดพิเศษ',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: 'images/privilege_movie_premiere.png',
        price: 500,
        rating: 4.9,
        reviews: 156,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        eventDate: '2024-06-15',
        venue: 'Major Cineplex Paragon',
        description: 'Experience the premiere night with VIP seating, welcome drinks, and exclusive meet & greet opportunity.',
        descriptionTh: 'สัมผัสประสบการณ์รอบปฐมทัศน์พร้อมที่นั่ง VIP เครื่องดื่มต้อนรับ และโอกาสพบปะทีมนักแสดง',
        conditions: ['Valid for 1 person', 'Non-transferable', 'Must present QR code at venue'],
        conditionsTh: ['ใช้ได้ 1 ท่าน', 'ไม่สามารถโอนสิทธิ์ได้', 'ต้องแสดง QR code ที่สถานที่']
    },
    {
        id: 102,
        title: 'Couple Movie Pass',
        titleTh: 'บัตรชมภาพยนตร์คู่รัก',
        subtitle: '2 tickets for any screening',
        subtitleTh: 'บัตร 2 ใบสำหรับทุกรอบฉาย',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: 'images/privilege_couple_movie.png',
        price: 300,
        rating: 4.7,
        reviews: 89,
        isPhysical: false,
        tier: 'silver',
        movieName: 'Any FLIPS Production',
        movieNameTh: 'ภาพยนตร์ FLIPS ทุกเรื่อง',
        description: 'Two premium tickets for any FLIPS production movie screening.',
        descriptionTh: 'บัตรพรีเมียม 2 ใบสำหรับภาพยนตร์ FLIPS ทุกเรื่อง',
        conditions: ['Valid for 2 persons', 'Valid for 6 months', 'Subject to seat availability'],
        conditionsTh: ['ใช้ได้ 2 ท่าน', 'ใช้ได้ภายใน 6 เดือน', 'ขึ้นอยู่กับที่นั่งว่าง']
    },
    {
        id: 103,
        title: 'Annual Movie Pass',
        titleTh: 'บัตรสมาชิกชมภาพยนตร์รายปี',
        subtitle: 'Unlimited movies for 1 year',
        subtitleTh: 'ดูหนังไม่จำกัดตลอด 1 ปี',
        category: 'movie-tickets',
        categoryLabel: 'Movie Tickets',
        categoryLabelTh: 'บัตรชมภาพยนตร์',
        image: 'images/privilege_annual_pass.png',
        price: 2000,
        rating: 5.0,
        reviews: 45,
        isPhysical: true,
        tier: 'gold',
        description: 'Unlimited access to all FLIPS production movies for one full year.',
        descriptionTh: 'เข้าชมภาพยนตร์ FLIPS ได้ไม่จำกัดตลอด 1 ปีเต็ม',
        conditions: ['Valid for 1 person', '12 months validity', 'Physical card will be shipped'],
        conditionsTh: ['ใช้ได้ 1 ท่าน', 'ใช้ได้ 12 เดือน', 'จัดส่งบัตรสมาชิกถึงบ้าน']
    },

    // Meet & Greet Category
    {
        id: 201,
        title: 'Director Meet & Greet',
        titleTh: 'พบปะผู้กำกับ',
        subtitle: 'Exclusive session with the director',
        subtitleTh: 'พบปะผู้กำกับแบบเอ็กซ์คลูซีฟ',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: 'images/privilege_meet_director.png',
        price: 1500,
        rating: 4.9,
        reviews: 32,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-07-20',
        venue: 'FLIPS Studio Bangkok',
        description: 'A once-in-a-lifetime opportunity to meet the director and discuss filmmaking.',
        descriptionTh: 'โอกาสครั้งหนึ่งในชีวิตที่จะพบผู้กำกับและพูดคุยเรื่องการสร้างภาพยนตร์',
        conditions: ['Limited to 20 participants', 'Photo opportunity included', 'Light refreshments provided'],
        conditionsTh: ['จำกัด 20 ท่าน', 'รวมถ่ายรูปร่วมกัน', 'มีอาหารว่างบริการ']
    },
    {
        id: 202,
        title: 'Cast Photo Session',
        titleTh: 'ถ่ายรูปกับนักแสดง',
        subtitle: 'Photo with main cast members',
        subtitleTh: 'ถ่ายรูปกับนักแสดงนำ',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: 'images/privilege_meet_cast.png',
        price: 800,
        rating: 4.8,
        reviews: 67,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-08-10',
        venue: 'FLIPS Studio Bangkok',
        description: 'Get your photo taken with the main cast members of the movie.',
        descriptionTh: 'ถ่ายรูปกับนักแสดงนำของภาพยนตร์',
        conditions: ['1 photo per person', 'Digital copy provided', 'Meet at designated time'],
        conditionsTh: ['1 รูปต่อท่าน', 'ได้รับไฟล์ดิจิตอล', 'นัดพบตามเวลาที่กำหนด']
    },
    {
        id: 203,
        title: 'Producer Dinner Event',
        titleTh: 'ดินเนอร์กับโปรดิวเซอร์',
        subtitle: 'Exclusive dinner with the producer',
        subtitleTh: 'รับประทานอาหารค่ำกับโปรดิวเซอร์',
        category: 'meet-greet',
        categoryLabel: 'Meet & Greet',
        categoryLabelTh: 'พบทีมผู้สร้างสรรค์',
        image: 'images/privilege_meet_private.png',
        price: 3000,
        rating: 5.0,
        reviews: 12,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-09-05',
        venue: 'The Peninsula Bangkok',
        description: 'An intimate dinner experience with the producer to discuss the creative process.',
        descriptionTh: 'ประสบการณ์รับประทานอาหารค่ำแบบส่วนตัวกับโปรดิวเซอร์',
        conditions: ['Limited to 10 guests', 'Formal dress code', 'Full course dinner included'],
        conditionsTh: ['จำกัด 10 ท่าน', 'แต่งกายสุภาพ', 'รวมอาหารค่ำเต็มคอร์ส']
    },

    // Movie Credits Category
    {
        id: 301,
        title: 'Special Thanks Credit',
        titleTh: 'เครดิต Special Thanks',
        subtitle: 'Your name in Special Thanks section',
        subtitleTh: 'ชื่อของคุณในส่วน Special Thanks',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: 'images/privilege_credits.png',
        price: 1000,
        rating: 4.8,
        reviews: 234,
        isPhysical: false,
        tier: 'silver',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'Have your name appear in the Special Thanks section of the movie credits.',
        descriptionTh: 'ชื่อของคุณจะปรากฏในส่วน Special Thanks ของเครดิตท้ายภาพยนตร์',
        conditions: ['Name as registered', 'Permanent credit', 'Certificate provided'],
        conditionsTh: ['ใช้ชื่อตามที่ลงทะเบียน', 'เครดิตถาวร', 'ได้รับใบประกาศนียบัตร']
    },
    {
        id: 302,
        title: 'Associate Producer Credit',
        titleTh: 'เครดิต Associate Producer',
        subtitle: 'Your name as Associate Producer',
        subtitleTh: 'ชื่อของคุณในฐานะ Associate Producer',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: 'images/privilege_credits_producer.png',
        price: 5000,
        rating: 5.0,
        reviews: 18,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'Be credited as an Associate Producer in the official movie credits.',
        descriptionTh: 'ได้รับเครดิตในฐานะ Associate Producer ในเครดิตภาพยนตร์อย่างเป็นทางการ',
        conditions: ['Official credit', 'IMDb listing', 'Premiere invitation included'],
        conditionsTh: ['เครดิตอย่างเป็นทางการ', 'ลงรายชื่อใน IMDb', 'รวมบัตรเชิญรอบปฐมทัศน์']
    },
    {
        id: 303,
        title: 'Executive Producer Credit',
        titleTh: 'เครดิต Executive Producer',
        subtitle: 'Top tier producer credit',
        subtitleTh: 'เครดิตโปรดิวเซอร์ระดับสูงสุด',
        category: 'credits',
        categoryLabel: 'Movie Credits',
        categoryLabelTh: 'เครดิตท้ายภาพยนตร์',
        image: 'images/privilege_credits_special.png',
        price: 15000,
        rating: 5.0,
        reviews: 5,
        isPhysical: false,
        tier: 'gold',
        movieName: 'The Great Journey',
        movieNameTh: 'การเดินทางที่ยิ่งใหญ่',
        description: 'The highest honor - be credited as Executive Producer with full privileges.',
        descriptionTh: 'เกียรติยศสูงสุด - ได้รับเครดิตในฐานะ Executive Producer พร้อมสิทธิพิเศษเต็มรูปแบบ',
        conditions: ['Prominent credit placement', 'All premiere events access', 'Private screening rights'],
        conditionsTh: ['เครดิตในตำแหน่งเด่น', 'เข้าร่วมงานปฐมทัศน์ทุกงาน', 'สิทธิ์ฉายภาพยนตร์ส่วนตัว']
    },

    // Merchandise Category
    {
        id: 401,
        title: 'Movie Poster Collection',
        titleTh: 'คอลเลคชั่นโปสเตอร์',
        subtitle: 'Signed limited edition posters',
        subtitleTh: 'โปสเตอร์ลิมิเต็ดพร้อมลายเซ็น',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: 'images/privilege_merch_poster.png',
        price: 400,
        rating: 4.7,
        reviews: 156,
        isPhysical: true,
        tier: 'silver',
        description: 'Set of 3 limited edition movie posters signed by the cast.',
        descriptionTh: 'ชุดโปสเตอร์ลิมิเต็ด 3 แบบพร้อมลายเซ็นนักแสดง',
        conditions: ['Ships within 7 days', 'Certificate of authenticity', 'Protective tube packaging'],
        conditionsTh: ['จัดส่งภายใน 7 วัน', 'ใบรับรองความแท้', 'บรรจุในหลอดป้องกัน']
    },
    {
        id: 402,
        title: 'Prop Replica Set',
        titleTh: 'ชุดพร็อพจำลอง',
        subtitle: 'Authentic prop replicas',
        subtitleTh: 'พร็อพจำลองจากภาพยนตร์',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: 'images/privilege_merch_tshirt.png',
        price: 800,
        rating: 4.9,
        reviews: 78,
        isPhysical: true,
        tier: 'gold',
        description: 'High-quality replica props used in the movie production.',
        descriptionTh: 'พร็อพจำลองคุณภาพสูงจากกองถ่ายภาพยนตร์',
        conditions: ['Handcrafted items', 'Display case included', 'Limited edition numbering'],
        conditionsTh: ['ทำมืออย่างประณีต', 'รวมกล่องแสดง', 'มีหมายเลขลิมิเต็ด']
    },
    {
        id: 403,
        title: 'Premium Merchandise Box',
        titleTh: 'กล่องสินค้าพรีเมียม',
        subtitle: 'Complete collector box set',
        subtitleTh: 'ชุดกล่องสะสมครบเซ็ต',
        category: 'merchandise',
        categoryLabel: 'Merchandise',
        categoryLabelTh: 'สินค้าที่ระลึก',
        image: 'images/privilege_merch_premium.png',
        price: 1500,
        rating: 5.0,
        reviews: 34,
        isPhysical: true,
        tier: 'gold',
        description: 'Complete box set with T-shirt, poster, art book, and exclusive items.',
        descriptionTh: 'กล่องครบเซ็ตพร้อมเสื้อยืด โปสเตอร์ อาร์ตบุ๊ค และของพิเศษ',
        conditions: ['All items included', 'Premium packaging', 'Numbered collector edition'],
        conditionsTh: ['รวมสินค้าทั้งหมด', 'บรรจุภัณฑ์พรีเมียม', 'เวอร์ชั่นสะสมมีหมายเลข']
    },

    // Behind the Scenes Category
    {
        id: 501,
        title: 'Set Visit Pass',
        titleTh: 'บัตรเยี่ยมชมกองถ่าย',
        subtitle: 'Full day set visit',
        subtitleTh: 'เยี่ยมชมกองถ่ายเต็มวัน',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: 'images/privilege_bts_set.png',
        price: 2000,
        rating: 5.0,
        reviews: 23,
        isPhysical: false,
        tier: 'gold',
        eventDate: '2024-08-15',
        venue: 'FLIPS Film Studios',
        description: 'Exclusive access to visit the movie set during production.',
        descriptionTh: 'สิทธิ์พิเศษในการเยี่ยมชมกองถ่ายระหว่างการผลิต',
        conditions: ['NDA required', 'No personal photography', 'Lunch provided'],
        conditionsTh: ['ต้องเซ็นสัญญารักษาความลับ', 'ห้ามถ่ายรูปส่วนตัว', 'รวมอาหารกลางวัน']
    },
    {
        id: 502,
        title: 'Behind the Scenes Documentary',
        titleTh: 'สารคดีเบื้องหลัง',
        subtitle: 'Exclusive documentary access',
        subtitleTh: 'เข้าถึงสารคดีพิเศษ',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: 'images/privilege_bts_makeup.png',
        price: 300,
        rating: 4.8,
        reviews: 189,
        isPhysical: false,
        tier: 'bronze',
        description: 'Access to exclusive behind-the-scenes documentary content.',
        descriptionTh: 'เข้าถึงเนื้อหาสารคดีเบื้องหลังพิเศษ',
        conditions: ['Digital streaming access', 'Lifetime access', 'HD quality'],
        conditionsTh: ['รับชมผ่านสตรีมมิ่ง', 'เข้าถึงตลอดชีพ', 'คุณภาพ HD']
    },
    {
        id: 503,
        title: 'VFX Studio Tour',
        titleTh: 'ทัวร์สตูดิโอ VFX',
        subtitle: 'Visual effects studio experience',
        subtitleTh: 'สัมผัสสตูดิโอเอฟเฟกต์พิเศษ',
        category: 'behind-scenes',
        categoryLabel: 'Behind the Scenes',
        categoryLabelTh: 'ชมเบื้องหลัง',
        image: 'images/privilege_bts_vip.png',
        price: 1200,
        rating: 4.9,
        reviews: 45,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-09-20',
        venue: 'FLIPS VFX Studio',
        description: 'Tour the VFX studio and see how movie magic is created.',
        descriptionTh: 'ทัวร์สตูดิโอ VFX และชมการสร้างมายากลภาพยนตร์',
        conditions: ['2-hour guided tour', 'Small group experience', 'Demonstration included'],
        conditionsTh: ['ทัวร์พร้อมไกด์ 2 ชั่วโมง', 'กลุ่มเล็กเป็นกันเอง', 'รวมการสาธิต']
    },

    // Other Privileges Category
    {
        id: 601,
        title: 'Script Reading Session',
        titleTh: 'เซสชั่นอ่านบท',
        subtitle: 'Attend a live script reading',
        subtitleTh: 'ร่วมฟังการอ่านบทสด',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: 'images/privilege_wrap_party.png',
        price: 600,
        rating: 4.7,
        reviews: 67,
        isPhysical: false,
        tier: 'silver',
        eventDate: '2024-07-10',
        venue: 'FLIPS Theater',
        description: 'Attend an exclusive script reading with the cast.',
        descriptionTh: 'ร่วมฟังการอ่านบทพิเศษกับทีมนักแสดง',
        conditions: ['Limited seating', 'Q&A session included', 'Refreshments served'],
        conditionsTh: ['ที่นั่งจำกัด', 'รวมเซสชั่นถาม-ตอบ', 'มีเครื่องดื่มบริการ']
    },
    {
        id: 602,
        title: 'Soundtrack Album',
        titleTh: 'อัลบั้มเพลงประกอบ',
        subtitle: 'Exclusive signed soundtrack',
        subtitleTh: 'อัลบั้มเพลงประกอบพร้อมลายเซ็น',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: 'images/privilege_screening.png',
        price: 350,
        rating: 4.6,
        reviews: 123,
        isPhysical: true,
        tier: 'bronze',
        description: 'Limited edition soundtrack album signed by the composer.',
        descriptionTh: 'อัลบั้มเพลงประกอบลิมิเต็ดพร้อมลายเซ็นนักแต่งเพลง',
        conditions: ['Vinyl + Digital', 'Signed by composer', 'Shipping included'],
        conditionsTh: ['แผ่นเสียง + ดิจิตอล', 'ลายเซ็นนักแต่งเพลง', 'รวมค่าจัดส่ง']
    },
    {
        id: 603,
        title: 'Investor Newsletter',
        titleTh: 'จดหมายข่าวผู้ลงทุน',
        subtitle: 'Exclusive monthly updates',
        subtitleTh: 'อัพเดทรายเดือนพิเศษ',
        category: 'other',
        categoryLabel: 'Other Privileges',
        categoryLabelTh: 'สิทธิพิเศษอื่นๆ',
        image: 'images/privilege_mystery.png',
        price: 100,
        rating: 4.5,
        reviews: 234,
        isPhysical: false,
        tier: 'bronze',
        description: 'Monthly exclusive newsletter with insider updates and early announcements.',
        descriptionTh: 'จดหมายข่าวรายเดือนพร้อมข้อมูลวงในและประกาศล่วงหน้า',
        conditions: ['12-month subscription', 'Digital delivery', 'Early access to news'],
        conditionsTh: ['สมัครสมาชิก 12 เดือน', 'ส่งทางดิจิตอล', 'รับข่าวก่อนใคร']
    }
];

// Calculate category counts
function getCategoryCounts() {
    const counts = {};
    privilegeCategories.forEach(cat => {
        if (cat.id === 'all') {
            counts[cat.id] = privilegePackages.length;
        } else {
            counts[cat.id] = privilegePackages.filter(p => p.category === cat.id).length;
        }
    });
    return counts;
}
